---
title: "Memory vs Sleep Phases"
toc: true
date: today
author: "Natallia Halai and Angela Textor"
format: 
  html:
    embed-resources: true
    code-fold: true
    number-sections: true
    
editor: visual
editor_options:
  chunk-output-type: console
  
project:
  output-dir: output
  execute-dir: project
  
execute: 
  warning: false
  error: false
  freeze: false
---

:::{comment_to_self}

One NA value from participant 9 epoch 58 was replaced by N1 

:::
```{r}
#| label: library_loading
#| include: false

library(ggplot2)
library(ggfortify)
library(dplyr)
library(GGally)
library(DHARMa)
library(tidyverse)

```


```{r}
#| label: data-loading
#| include: false

condition<-read_csv("data/processed/Condition_participants.csv", 
    col_types = cols(participant_id = col_factor(levels = c("1", 
        "2", "3", "4", "5", "6", "7", "8",
        "9")), Condition = col_factor(levels = c("Coffein", 
        "None"))))

all_scoring <- read_csv("data/processed/scoring_processed/all_scoring.csv", 
col_types = cols(stage = col_factor(levels = c("Wake", "N1", "N2", "N3", "REM")), digit = col_skip()))

all_olt<-read_csv("data/processed/olt_processed/all_olt.csv", 
    col_types = cols(participant = col_factor(levels = c("1", 
        "2", "3", "4", "5", "6", "7", "8", 
        "9")), timepoint = col_factor(levels = c("1", 
        "2")), file = col_skip()))

all_olt$condition<-rep(condition$Condition, each=2)
all_scoring$participant<-factor(all_scoring$participant, levels=c(1,2,3,4,5,6,7,8,9))
all_scoring$condition<-ifelse(all_scoring$participant %in% c(1, 5, 6, 9), "Coffein", "None")

```


# Per Participant Sleep Stage Duration
```{r}
#| label: extraction-Phases

#length of each sleep stage per participant
number_stages<-table(all_scoring$participant, all_scoring$stage)
number_stages<-number_stages*30
number_stages<-data.frame(number_stages)
number_stages<-number_stages%>%
  rename(Participant=Var1, Stage=Var2, Time=Freq)

#Adding the time for Wake in 3
number_stages[number_stages$Participant==3 & number_stages$Stage=="Wake",]$Time<-2880


ggplot(number_stages, aes(x=Participant, y=Time/60, fill=Stage))+
  geom_bar(stat="identity")+
  scale_fill_manual(values=c(
    "Wake"= "lightsalmon",
    "N1"="lightgoldenrod1",
    "N2"="lightgreen",
    "N3"="lightskyblue",
    "REM"="violet"
  ))+
  ylab("Time (min)")+
  theme_light()


```


# Per Condition Sleep Stage Duration
```{r}
number_times_condition<-table(all_scoring$condition, all_scoring$stage)*30
number_times_condition[2,1]<-number_times_condition[2,1]+2880 #adding the missing participant 3s data of Wake

number_times_condition<-data.frame(number_times_condition)

number_times_condition<-number_times_condition%>%
  rename(Condition=Var1, Stage=Var2, Time=Freq)

number_times_condition$Condition<-ifelse(number_times_condition$Condition=="None", 0, 1)
number_times_condition$Condition<-factor(number_times_condition$Condition, levels=c(0,1), labels=c("None", "Coffein"))


ggplot(number_times_condition, aes(x=Condition, y=Time/60, fill=Stage))+
  geom_bar(stat="identity")+
  scale_fill_manual(values=c(
    "Wake"= "lightsalmon",
    "N1"="lightgoldenrod1",
    "N2"="lightgreen",
    "N3"="lightskyblue",
    "REM"="violet"
  ))+
  ylab("Time (min)")+
  theme_light()

```


# T tests for each sleep stage
```{r}
number_stages$condition<-ifelse(number_stages$Participant %in% c(1,5,6,9), 1, 0)
number_stages$condition<-factor(number_stages$condition, levels=c(0,1), labels=c("None", "Coffein"))

t.test(Time~condition, data = subset(number_stages, Stage == "Wake"))
t.test(Time~condition, data = subset(number_stages, Stage == "N1"))
t.test(Time~condition, data = subset(number_stages, Stage == "N2"))
t.test(Time~condition, data = subset(number_stages, Stage == "N3"))

```


# Models:

## Overfitting models 
```{r}
#can the model predict the improvement/no improvement in the memory test based on the time asleep in phases and the conditioning of the patients

all_olt_new <- all_olt %>% 
  select(-time_for_answer_correct)

all_olt_wide <- all_olt_new %>% 
  pivot_wider(names_from = timepoint, values_from = percent_correct) #making new columns with the values from percent

all_olt_wide$difference<-all_olt_wide%>%
  group_by(participant)%>%
  reframe(extra_diff= `2`-`1`,
          x=factor(0))

#adding the phases time sleep into the wide data frame

number_stages_wide<-number_stages%>%
  pivot_wider(names_from = Stage, values_from = Time)

all_olt_wide<-all_olt_wide%>%
  rename(Participant="participant")

#final dataset with all information for a logistic regression
all_olt_stages_wide<-left_join(all_olt_wide, number_stages_wide, by=c("Participant","condition"))
all_olt_stages_wide$condition<-factor(all_olt_stages_wide$condition, levels=c("None", "Coffein"))


#Overfitting models:

model1<-lm(`2`~`1`+condition+Wake+N1+N2+N3, data=all_olt_stages_wide)
summary(model1) # -> high R squared -> overfitting risk

model2<-lm(`2`~`1`+Wake+N1+N2+N3, data=all_olt_stages_wide)
summary(model2)

```


## Combination of variables -> deep sleep stage model
```{r}

all_olt_stages_wide$deep_sleep<-all_olt_stages_wide$N2+all_olt_stages_wide$N3
all_olt_stages_wide$difference<-all_olt_stages_wide$`2`- all_olt_stages_wide$`1`

#Mdel
model3<-lm(difference~deep_sleep+ condition, data=all_olt_stages_wide)
sum_m3<-summary(model3) 

knitr::kable(sum_m3$coefficients)

ggplot(all_olt_stages_wide, aes(x=deep_sleep, y=difference))+
  geom_point()+
  geom_smooth(method="lm")+
  xlab("Time in deep sleep")+
  ylab("Difference in memory score")+
  theme_light()

(cor(all_olt_stages_wide$deep_sleep, all_olt_stages_wide$difference))


```

